apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: dev
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-app
    spec:
      containers:
        - name: web-app
          image: 339712873727.dkr.ecr.eu-north-1.amazonaws.com/web-app:dev
          ports:
            - containerPort: 5000
          envFrom:
          - secretRef:
              name: env-config
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  namespace: dev
spec:
  selector:
    app.kubernetes.io/name: web-app
  ports:
    - port: 80
      targetPort: 5000
  type: NodePort