apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-dev
  region: eu-north-1

fargateProfiles:
  - name: fp-reverse-ip
    selectors:
      # All workloads in the "dev" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: dev
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
    subnets:
      - subnet-0580f97ac94f1d328
      - subnet-086b654104b1a330a