
# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-dev
  region: eu-north-1

vpc:
  id: "vpc-06bc17b92e2453fb7"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  securityGroup: "sg-01fe85f87a65b0639" #Additional security group
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      eu-north-1a:
        id: "subnet-0ce3614ccf44fb75d"
        cidr: "10.0.0.0/20" # (optional, must match CIDR used by the given subnet)

      eu-north-1b:
        id: "subnet-03c9c50afa9d901fa"
        cidr: "10.0.16.0/20"  # (optional, must match CIDR used by the given subnet)

fargateProfiles:
  - name: fp-reverse-ip
    selectors:
      # All workloads in the "dev" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: dev
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
    subnets:
      - subnet-0580f97ac94f1d328
      - subnet-086b654104b1a330a